name: Build Android APK
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Set up Java Executor
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Android SDK & NDK
        uses: android-actions/setup-android@v3

      - name: Install NDK Component
        run: sdkmanager "ndk;26.1.10909125"

      - name: Compile App with Gradle
        run: |
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Upload Finished APK
        uses: actions/upload-artifact@v4
        with:
          name: Pong-Game-APK
          path: app/build/outputs/apk/debug/app-debug.apk
