name: Build Android APK
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Set up Java Environment
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Fetch Pure Native SDL Framework
        run: |
          git clone --branch SDL2 --depth 1 https://github.com/libsdl-org/SDL.git sdl2-source
          mkdir -p app/jni
          cp -r sdl2-source/android-project/* .
          cp -r sdl2-source app/jni/sdl
          rm -rf sdl2-source

      - name: Inject Game Logic
        run: |
          mkdir -p app/jni/src
          rm -rf app/jni/src/*
          cp main.cpp app/jni/src/main.cpp
          
          # Remove duplicate source files causing the Java compiler to choke
          rm -f app/src/main/java/org/libsdl/app/SDLInputConnection.java

      - name: Build Standalone APK
        run: |
          chmod +x gradlew
          ./gradlew assembleDebug -Pandroid.injected.build.abi="arm64-v8a,armeabi-v7a"


      - name: Upload Finished Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Pong-Game-APK
          path: "**/build/outputs/apk/**/*.apk"

